apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-worker-edit
  namespace: techchallenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-worker-edit
  template:
    metadata:
      labels:
        app: service-worker-edit
    spec:
      containers:
        - name: service-worker-edit
          image: tech-challenge-service-worker-edit
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
