apiVersion: v1
kind: Service
metadata:
  name: service-worker-edit
  namespace: techchallenge
spec:
  type: NodePort
  selector:
    app: service-worker-edit
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30883  # Expor via localhost:30889
