apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: techchallenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
        - name: sqlserver
          image: custom-sqlserver:latest  # sua imagem personalizada
          imagePullPolicy: Never
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "YourStrong!Passw0rd"
