apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
  namespace: techchallenge
spec:
  type: NodePort
  selector:
    app: sqlserver
  ports:
    - name: sql
      port: 1433
      targetPort: 1433
      nodePort: 31433  # você acessa no host usando localhost:31433
