apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: techchallenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prometheus-local
          imagePullPolicy: Never
          ports:
            - containerPort: 9090
          volumeMounts:
            - mountPath: /data
              name: prometheus-storage
      volumes:
        - name: prometheus-storage
          emptyDir: {}
