services:
  api:
    build:
      context: ./TechChallengeFiap  # Caminho para a pasta onde está o Dockerfile
      dockerfile: Dockerfile        # (opcional) Especifica o arquivo Dockerfile  
      args:
           version: 1
    image: tech-challenge-metrics
    ports:
      - 8888:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=ContactDB;User=sa;Password=YourStrong!Passw0rd;
    depends_on:
      - sqlserver
      - rabbitmq
    networks:
      - tech_challenge_metrics_network

  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    networks:
      - tech_challenge_metrics_network
    volumes:
      - sql_data:/var/opt/mssql

  rabbitmq:
    image: "rabbitmq:management" # Imagem com a interface de gerenciamento do RabbitMQ
    ports:
      - "15672:15672" # Interface de gerenciamento RabbitMQ
      - "5672:5672" # Porta para comunicação de mensageria
    environment:
      RABBITMQ_DEFAULT_USER: guest # Usuário default
      RABBITMQ_DEFAULT_PASS: guest # Senha do usuário

  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
      args:
        version: 1
    image: prometheus-local
    restart: always
    ports: 
      - 9090:9090
    networks:
      - tech_challenge_metrics_network
    volumes: 
      - './prometheus/data:/data'
  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
      args:
        version: 1
    image: grafana-local
    restart: always
    ports:
      - 3000:3000
    networks: 
      - tech_challenge_metrics_network

networks:
  tech_challenge_metrics_network:
    driver: bridge
    attachable: true

volumes:
  sql_data: