services:
  api:
    build:
      context: ./TechChallengeFiap
      dockerfile: Dockerfile
      args:
        version: 1
    image: tech-challenge-metrics
    ports:
      - 8888:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - tech_challenge_metrics_network
  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
      args:
        version: 1
    image: prometheus-local
    restart: always
    ports: 
      - 9090:9090
    networks:
      - tech_challenge_metrics_network
    volumes: 
      - './prometheus/data:/data'
  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
      args:
        version: 1
    image: grafana-local
    restart: always
    ports:
      - 3000:3000
    networks: 
      - tech_challenge_metrics_network
networks:
  tech_challenge_metrics_network:
    driver: bridge
    attachable: true