apiVersion: v1
kind: Service
metadata:
  name: api-consulta-service
  namespace: techchallenge
spec:
  type: NodePort
  selector:
    app: api-consulta
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30891  # Expor via localhost:30889