apiVersion: v1
kind: Service
metadata:
  name: service-worker-delete
  namespace: techchallenge
spec:
  type: NodePort
  selector:
    app: service-worker-delete
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30884  # Expor via localhost:30889
