apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-add
  namespace: techchallenge
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-add
  template:
    metadata:
      labels:
        app: api-add
    spec:
      containers:
        - name: api-add
          image: tech-challenge-add
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production