apiVersion: v1
kind: Service
metadata:
  name: api-add-service
  namespace: techchallenge
spec:
  type: NodePort
  selector:
    app: api-add
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30888  # Expor via localhost:30889