apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: techchallenge
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000  # <-- PORTA EXTERNA
