apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-delete
  namespace: techchallenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-delete
  template:
    metadata:
      labels:
        app: api-delete
    spec:
      containers:
        - name: api-delete
          image: tech-challenge-delete
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"

             # SQL Server
            - name: SQLSERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SQLSERVER_HOST
            - name: SQLSERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SQLSERVER_PORT
            - name: SQLSERVER_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SQLSERVER_USER
            - name: SQLSERVER_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SQLSERVER_PASSWORD
            - name: SQLSERVER_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SQLSERVER_DATABASE
