apiVersion: v1
kind: Service
metadata:
  name: api-delete-service
  namespace: techchallenge
spec:
  type: NodePort
  selector:
    app: api-delete
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30890  # Expor via localhost:30889
