apiVersion: v1
kind: Service
metadata:
  name: api-update
  namespace: techchallenge
spec:
  type: NodePort
  selector:
    app: api-update
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30886  # Expor via localhost:30889
