name: .NET Core CI

on:
  push:
    branches:
      - main # Dispara o pipeline em push para a branch main
  pull_request:
    branches:
      - main # Dispara o pipeline em pull requests para a branch main

jobs:
  build:
    runs-on: self-hosted

    steps:
    # Baixar o código do repositório
    - name: Checkout code
      uses: actions/checkout@v3

    # Configurar o .NET Core SDK
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Versão do SDK, ajuste conforme necessário

    # Restaurar dependências
    - name: Restore dependencies
      run: dotnet restore TechChallengeFiap/TechChallengeFiap.sln

    # Compilar o projeto
    - name: Build the project
      run: dotnet build TechChallengeFiap/TechChallengeFiap.sln --no-restore --configuration Release

    #- name: List files in the repository
    #  run: ls -R
      
    # Executar testes
    - name: Run tests
      run: dotnet test --no-build --verbosity normal
