name: .NET Core CI

on:
  push:
    branches:
      - main # Dispara o pipeline em push para a branch main
  pull_request:
    branches:
      - main # Dispara o pipeline em pull requests para a branch main

jobs:
  build:
    runs-on: self-hosted

    steps:
    # Baixar o código do repositório
    - name: Checkout code
      uses: actions/checkout@v3

    # Configurar o .NET Core SDK
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Versão do SDK, ajuste conforme necessário
        install-dir: C:\Tools\dotnet # Escolha um diretório com permissões apropriadas

    # Adicionar o .NET ao PATH
    - name: Add .NET to PATH
      run: |
        echo C:\Tools\dotnet > $env:PATH

    # Restaurar dependências
    - name: Restore dependencies
      run: dotnet restore

    # Compilar o projeto
    - name: Build the project
      run: dotnet build --no-restore --configuration Release

    # Executar testes
    - name: Run tests
      run: dotnet test --no-build --verbosity normal
