name: .NET Core CI

on:
  push:
    branches:
      - main # Dispara o pipeline em push para a branch main
  pull_request:
    branches:
      - main # Dispara o pipeline em pull requests para a branch main

jobs:
  build:
    runs-on: self-hosted
          
    steps:
    # Baixar o código do repositório
    - name: Checkout code
      uses: actions/checkout@v3

    # Configurar o .NET Core SDK
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Versão do SDK, ajuste conforme necessário
        
    # Restaurar dependências
    - name: Restore dependencies
      run: dotnet restore TechChallengeFiap/TechChallengeFiap.sln

    #- name: Aplicar migrations
    #  run: dotnet ef database update --project TechChallengeFiap/TechChallengeFiap.csproj
    
    - name: Executar migrações no SQL Server Local
      env:
            SQL_SERVER_HOST: GUSTAVO-PC
            SQL_SERVER_USER: sa
            SQL_SERVER_PASSWORD: 12345678
            SQL_SERVER_DB: ContactDB
      run: |
            # Verifique a conectividade com o SQL Server
            echo "Testando a conexão com o SQL Server..."
            sqlcmd -S $SQL_SERVER_HOST -U $SQL_SERVER_USER -P $SQL_SERVER_PASSWORD -d $SQL_SERVER_DB -Q "SELECT 1"
            
    # Compilar o projeto
    - name: Build the project
      run: dotnet build TechChallengeFiap/TechChallengeFiap.sln --no-restore --configuration Release

    - name: Build the test project
      run: dotnet build ./TechChallengeFiap.Tests/TechChallengeFiap.Tests.csproj --configuration Debug
      
    - name: Build the test integrated project
      run: dotnet build ./TechChallengeFiap.Tests.Integration/TechChallengeFiap.Tests.Integration.csproj --configuration Debug
      
    # Executar testes
    - name: Run tests
      run: dotnet test TechChallengeFiap.Tests/TechChallengeFiap.Tests.csproj --no-build --verbosity normal
      
    # Executar testes integrados
    - name: Run integrated tests
      run: dotnet test TechChallengeFiap.Tests.Integration/TechChallengeFiap.Tests.Integration.csproj --no-build --verbosity normal
